  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import { ReactNode } from "react"; 
  import { Anton } from 'next/font/google'


type RootLayoutProps = {
  children: ReactNode;
};

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  const anton = Anton({
    subsets: ['latin'],
    weight: '400', 
    variable: '--font-anton',
  })

  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }: RootLayoutProps) {
    return (
      <html lang="en" className={anton.variable}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>
            {/* <Navbar/> */}
          </header>

          <main>
            {children}
          </main>


          
        </body>
      </html>
    );
  }
